import {
  Analytics as AnalyticsIcon,
  Check as CheckIcon,
  Clear as ClearIcon,
  Delete as DeleteIcon,
  Edit as EditIcon,
  ExpandMore as ExpandMoreIcon,
  Refresh as RefreshIcon,
  Search as SearchIcon,
  Star as StarIcon,
  ThumbDown as ThumbDownIcon,
  ThumbUp as ThumbUpIcon,
} from '@mui/icons-material';
import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Divider,
  Grid,
  IconButton,
  Paper,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  TextField,
  Typography,
} from '@mui/material';
import { useEffect, useState } from 'react';
import {
  autoGenerateFAQFromQueries,
  deleteFAQQuestion,
  exportFAQsForMarketingSite,
  generateFAQSuggestions,
  getFAQCategories,
  getFAQStats,
  getPendingFAQs,
  getPublishedFAQs,
  reviewFAQQuestion,
  updateFAQQuestion,
  type FAQCategory,
  type FAQQuestion,
} from '../lib/faqService';

export default function FAQManagementPage() {
  const [pendingFAQs, setPendingFAQs] = useState<FAQQuestion[]>([]);
  const [publishedFAQs, setPublishedFAQs] = useState<FAQQuestion[]>([]);
  const [categories, setCategories] = useState<FAQCategory[]>([]);
  const [stats, setStats] = useState<any>(null);
  const [suggestions, setSuggestions] = useState<any[]>([]);
  const [searchTerm, setSearchTerm] = useState('');
  const [editDialogOpen, setEditDialogOpen] = useState(false);
  const [editingFAQ, setEditingFAQ] = useState<FAQQuestion | null>(null);
  const [editForm, setEditForm] = useState({ question: '', answer: '', category_id: '' });
  const [_autoGeneratedCount, setAutoGeneratedCount] = useState(0);
  const [message, setMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = () => {
    setPendingFAQs(getPendingFAQs());
    setPublishedFAQs(getPublishedFAQs());
    setCategories(getFAQCategories());
    setStats(getFAQStats());
    setSuggestions(generateFAQSuggestions(10));
  };

  const handleApprove = (faqId: string) => {
    if (reviewFAQQuestion(faqId, 'published')) {
      showMessage('success', 'FAQ已发布');
      loadData();
    }
  };

  const handleReject = (faqId: string) => {
    if (reviewFAQQuestion(faqId, 'archived')) {
      showMessage('success', 'FAQ已归档');
      loadData();
    }
  };

  const handleDelete = (faqId: string) => {
    if (window.confirm('确定要删除这个FAQ吗？')) {
      if (deleteFAQQuestion(faqId)) {
        showMessage('success', 'FAQ已删除');
        loadData();
      }
    }
  };

  const handleEdit = (faq: FAQQuestion) => {
    setEditingFAQ(faq);
    setEditForm({
      question: faq.question,
      answer: faq.answer,
      category_id: faq.category_id || '',
    });
    setEditDialogOpen(true);
  };

  const handleSaveEdit = () => {
    if (editingFAQ) {
      if (updateFAQQuestion(editingFAQ.id, editForm)) {
        showMessage('success', 'FAQ已更新');
        setEditDialogOpen(false);
        setEditingFAQ(null);
        loadData();
      }
    }
  };

  const handleAutoGenerate = () => {
    const count = autoGenerateFAQFromQueries();
    setAutoGeneratedCount(count);
    showMessage('success', `已生成 ${count} 个FAQ草稿`);
    loadData();
  };

  const handleExport = () => {
    const data = exportFAQsForMarketingSite();
    if (data) {
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `faqs-export-${new Date().toISOString().split('T')[0]}.json`;
      a.click();
      URL.revokeObjectURL(url);
      showMessage('success', 'FAQ已导出');
    }
  };

  const showMessage = (type: 'success' | 'error', text: string) => {
    setMessage({ type, text });
    setTimeout(() => setMessage(null), 3000);
  };

  const getCategoryName = (categoryId?: string) => {
    const category = categories.find(c => c.id === categoryId);
    return category?.name || '未分类';
  };

  return (
    <Box>
      {/* 页面标题 */}
      <Box sx={{ mb: 3 }}>
        <Typography variant="h4" component="h1" sx={{ fontWeight: 700, mb: 1 }}>
          📝 FAQ 管理
        </Typography>
        <Typography variant="body1" color="text.secondary">
          管理和审核常见问题，自动从用户对话中收集高频问题
        </Typography>
      </Box>

      {/* 消息提示 */}
      {message && (
        <Alert severity={message.type} sx={{ mb: 2 }} onClose={() => setMessage(null)}>
          {message.text}
        </Alert>
      )}

      {/* 统计卡片 */}
      {stats && (
        <Grid container spacing={2} sx={{ mb: 3 }}>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card>
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  总问题数
                </Typography>
                <Typography variant="h4">{stats.totalQuestions}</Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card>
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  已发布
                </Typography>
                <Typography variant="h4" color="success.main">
                  {stats.publishedQuestions}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card>
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  待审核
                </Typography>
                <Typography variant="h4" color="warning.main">
                  {stats.pendingReview}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card>
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  自动收集
                </Typography>
                <Typography variant="h4" color="info.main">
                  {stats.autoCollected}
                </Typography>
              </CardContent>
            </Card>
          </Grid>
          <Grid item xs={12} sm={6} md={2.4}>
            <Card>
              <CardContent>
                <Typography variant="body2" color="text.secondary">
                  有用率
                </Typography>
                <Typography variant="h4" color="primary.main">
                  {stats.avgHelpfulness.toFixed(1)}%
                </Typography>
              </CardContent>
            </Card>
          </Grid>
        </Grid>
      )}

      {/* 操作栏 */}
      <Paper sx={{ p: 2, mb: 3 }}>
        <Box sx={{ display: 'flex', gap: 2, flexWrap: 'wrap', alignItems: 'center' }}>
          <Button
            variant="outlined"
            startIcon={<RefreshIcon />}
            onClick={loadData}
          >
            刷新
          </Button>
          <Button
            variant="contained"
            startIcon={<AnalyticsIcon />}
            onClick={handleAutoGenerate}
            color="info"
          >
            自动生成FAQ
          </Button>
          <Button
            variant="outlined"
            startIcon={<StarIcon />}
            onClick={handleExport}
          >
            导出JSON
          </Button>
          <Box sx={{ flexGrow: 1 }} />
          <TextField
            size="small"
            placeholder="搜索FAQ..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            InputProps={{
              startAdornment: <SearchIcon sx={{ mr: 1, color: 'text.secondary' }} />,
            }}
            sx={{ width: 250 }}
          />
        </Box>
      </Paper>

      {/* 高频查询建议 */}
      {suggestions.length > 0 && (
        <Card sx={{ mb: 3, bgcolor: 'info.50' }}>
          <CardContent>
            <Typography variant="h6" gutterBottom>
              💡 高频查询建议（可自动生成FAQ）
            </Typography>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
              {suggestions.map((suggestion, index) => (
                <Box key={index} sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
                  <Chip label={`${suggestion.occurrence_count}次`} size="small" color="info" />
                  <Typography variant="body2">{suggestion.query_text}</Typography>
                  <Chip label={getCategoryName(categories.find(c => c.slug === suggestion.suggested_category)?.id)} size="small" />
                </Box>
              ))}
            </Box>
          </CardContent>
        </Card>
      )}

      {/* 待审核列表 */}
      <Card sx={{ mb: 3 }}>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            ⏳ 待审核 ({pendingFAQs.length})
          </Typography>
          <Divider sx={{ mb: 2 }} />
          
          {pendingFAQs.length === 0 ? (
            <Typography color="text.secondary" textAlign="center" py={4}>
              暂无待审核的FAQ
            </Typography>
          ) : (
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2 }}>
              {pendingFAQs.map((faq) => (
                <Accordion key={faq.id}>
                  <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, width: '100%' }}>
                      <Chip 
                        label={faq.source_type === 'auto_collected' ? '自动收集' : '手动'} 
                        size="small" 
                        color={faq.source_type === 'auto_collected' ? 'info' : 'default'}
                      />
                      <Typography>{faq.question}</Typography>
                    </Box>
                  </AccordionSummary>
                  <AccordionDetails>
                    <Box sx={{ mb: 2 }}>
                      <Typography variant="body2" color="text.secondary" gutterBottom>
                        答案：
                      </Typography>
                      <Typography variant="body2">{faq.answer}</Typography>
                    </Box>
                    <Box sx={{ display: 'flex', gap: 1, mb: 2 }}>
                      <Chip label={`分类: ${getCategoryName(faq.category_id)}`} size="small" />
                      {faq.tags && faq.tags.map(tag => (
                        <Chip key={tag} label={tag} size="small" variant="outlined" />
                      ))}
                    </Box>
                    <Box sx={{ display: 'flex', gap: 1 }}>
                      <Button
                        size="small"
                        variant="contained"
                        startIcon={<CheckIcon />}
                        onClick={() => handleApprove(faq.id)}
                        color="success"
                      >
                        通过
                      </Button>
                      <Button
                        size="small"
                        variant="outlined"
                        startIcon={<ClearIcon />}
                        onClick={() => handleReject(faq.id)}
                        color="error"
                      >
                        拒绝
                      </Button>
                      <Button
                        size="small"
                        variant="outlined"
                        startIcon={<EditIcon />}
                        onClick={() => handleEdit(faq)}
                      >
                        编辑
                      </Button>
                    </Box>
                  </AccordionDetails>
                </Accordion>
              ))}
            </Box>
          )}
        </CardContent>
      </Card>

      {/* 已发布列表 */}
      <Card>
        <CardContent>
          <Typography variant="h6" gutterBottom>
            ✅ 已发布 ({publishedFAQs.length})
          </Typography>
          <Divider sx={{ mb: 2 }} />
          
          {publishedFAQs.length === 0 ? (
            <Typography color="text.secondary" textAlign="center" py={4}>
              暂无已发布的FAQ
            </Typography>
          ) : (
            <TableContainer>
              <Table size="small">
                <TableHead>
                  <TableRow>
                    <TableCell>问题</TableCell>
                    <TableCell>分类</TableCell>
                    <TableCell align="center">查看</TableCell>
                    <TableCell align="center">有用</TableCell>
                    <TableCell align="right">操作</TableCell>
                  </TableRow>
                </TableHead>
                <TableBody>
                  {publishedFAQs
                    .filter(faq => 
                      !searchTerm || 
                      faq.question.toLowerCase().includes(searchTerm.toLowerCase())
                    )
                    .map((faq) => (
                      <TableRow key={faq.id}>
                        <TableCell>{faq.question}</TableCell>
                        <TableCell>{getCategoryName(faq.category_id)}</TableCell>
                        <TableCell align="center">{faq.view_count}</TableCell>
                        <TableCell align="center">
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5, justifyContent: 'center' }}>
                            <ThumbUpIcon fontSize="small" color="success" />
                            {faq.helpful_count}
                            <ThumbDownIcon fontSize="small" color="error" />
                            {faq.not_helpful_count}
                          </Box>
                        </TableCell>
                        <TableCell align="right">
                          <IconButton size="small" onClick={() => handleEdit(faq)}>
                            <EditIcon />
                          </IconButton>
                          <IconButton size="small" onClick={() => handleDelete(faq.id)} color="error">
                            <DeleteIcon />
                          </IconButton>
                        </TableCell>
                      </TableRow>
                    ))}
                </TableBody>
              </Table>
            </TableContainer>
          )}
        </CardContent>
      </Card>

      {/* 编辑对话框 */}
      <Dialog open={editDialogOpen} onClose={() => setEditDialogOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle>编辑FAQ</DialogTitle>
        <DialogContent>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, mt: 2 }}>
            <TextField
              label="问题"
              multiline
              rows={2}
              fullWidth
              value={editForm.question}
              onChange={(e) => setEditForm({ ...editForm, question: e.target.value })}
            />
            <TextField
              label="答案"
              multiline
              rows={6}
              fullWidth
              value={editForm.answer}
              onChange={(e) => setEditForm({ ...editForm, answer: e.target.value })}
            />
            <TextField
              select
              label="分类"
              fullWidth
              SelectProps={{ native: true }}
              value={editForm.category_id}
              onChange={(e) => setEditForm({ ...editForm, category_id: e.target.value })}
            >
              <option value="">未分类</option>
              {categories.map(cat => (
                <option key={cat.id} value={cat.id}>{cat.name}</option>
              ))}
            </TextField>
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setEditDialogOpen(false)}>取消</Button>
          <Button onClick={handleSaveEdit} variant="contained">保存</Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
